### ISSUE TITLE
Compiler target set too high (1.5 suffices)

### ISSUE THREAD

**Issue by jdhoek** [svenkubiak/jBCrypt#1]
The `BCrypt` code wrapped by this package compiles fine with a compiler target of `1.5`, but this package's POM sets it to `1.8`. This unfortunately means that JDK 1.8 is the minimum requirement for the artifacts released on Maven Central, even though the code itself works fine with JDK 1.5.

**Comment by svenkubiak** [comment]
>This unfortunately means that JDK 1.8 is the minimum requirement for the artifacts released on Maven >Central

Although the code would compile fine, thats intentional. Java 1.5 reached EOL in October 2009, 1.6 in February 2013 and 1.7 will reach EOL in May 2015. So, IMHO, its time to move on ;-)

**Comment by mnn** [comment]
No, it's not. Not as long as there are crowds of Android devices (more than a third) being used for which library compiled against 1.8 cannot be used.
