### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by Zetten** [svenkubiak/jBCrypt#2]
The readme states

> jBCrypt is licensed under a ISC/BSD licence. See the LICENSE file for details.

but said file doesn't exist.

Given the clause from https://github.com/jeremyh/jBCrypt/blob/master/LICENSE that reads "provided that the above copyright notice and this permission notice appear in all copies" I think it needs to be added :smile:

**Comment by svenkubiak** [comment]
Added.
