### ISSUE TITLE
Clarify "moved to a java package" in README

### ISSUE THREAD

**Issue by benmccann** [svenkubiak/jBCrypt#3]
You say:

>The classes have been moved to a java package to avoid pollution of the global namespace. org.mindrot was chosen to reflect their original origin.

However, when I download http://www.mindrot.org/files/jBCrypt/jBCrypt-0.4.zip I see that the first line in BCrypt.java is "package org.mindrot.jbcrypt;". So what do you mean that the classes have been moved to a java package? They seem to already be in a Java package to me.

**Comment by svenkubiak** [comment]
I have basically copied the readme from this project:
https://github.com/jeremyh/jBCrypt

I have created this project basically becaus the found maven package for jBcrypt were outdated at maven central and I needed files that where up to date.

As for the package. I will remove the line from the readme asap.
