### ISSUE TITLE
char[] instead of String?

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [svenkubiak/jBCrypt#6]
Hi there,

Thanks for your work on this. 

I'd like to ask, is there any reason `hashpw` method works with `String` instead of `char[]`? Wouldn't it be better if array was used, as it's not interned and may be removed from memory?

**Comment by svenkubiak** [comment]
Hi,

char[] instrad of string sounds reasonable. But this repository is just a wrapper for the original source code found at http://www.mindrot.org/projects/jBCrypt/ - i'll just provide the access to a maven repository for easy use of the JBCrypt code from Damien Miller. Feel free to get in contact with him.
